ARCH-1916 - Tweaks from testing

diff --git a/.github/workflows/reusable-build-and-review-pr.yml b/.github/workflows/reusable-build-and-review-pr.yml
--- a/.github/workflows/reusable-build-and-review-pr.yml
+++ b/.github/workflows/reusable-build-and-review-pr.yml
@@ -17,7 +17,7 @@ on:
         description: The location of the readme file
         required: false
         type: string
-        default: './README.md'
+        default: 'README.md'
       files-with-code:
         description: The files that contain code for the action
         required: false
@@ -42,6 +42,11 @@ jobs:
       NEXT_VERSION: ${{ steps.version.outputs.NEXT_VERSION }}
 
     steps:
+      - name: Dump GitHub context
+        env:
+          GITHUB_CONTEXT: ${{ toJson(github) }}
+        run: echo "$GITHUB_CONTEXT"
+        
       - name: Checkout
         uses: actions/checkout@v3
         with:
@@ -59,9 +64,9 @@ jobs:
       - name: Action Source Code Changed - ${{ steps.source-code.outputs.HAS_CHANGES }}
         run: |
           if [ "${{ steps.source-code.outputs.HAS_CHANGES }}" == "true" ]; then
-            echo "The PR changes the action's source code.  Proceed with subsequent steps."
+            echo "This PR changes the action's source code.  Proceed with subsequent steps."
           else
-            echo "The PR does not change the action's source code.  Skipping subsequent steps."
+            echo "This PR does not change the action's source code.  Skipping subsequent steps."
           fi
 
       - name: Get the next version for the repo
@@ -83,15 +88,16 @@ jobs:
       IS_FORK: ${{ github.event.pull_request.head.repo.fork }}
       PR_SOURCE: ${{ github.event.pull_request.head.repo.fork == true && 'fork' || 'branch' }}
       NEEDS_COMMIT: false
+      HAS_BUILD_STEP: false
       FAILURE_MESSAGE: ''
 
     steps:
       - name: Action Source Code Changed - ${{ env.HAS_CODE_CHANGES }}
         run: |
           if [ "${{env.HAS_CODE_CHANGES}}" == "true" ]; then
-            echo "The PR changes the action's source code.  Proceed with subsequent steps and jobs."
+            echo "This PR changes the action's source code.  Proceed with subsequent steps and jobs."
           else
-            echo "The PR does not change the action's source code.  Skipping subsequent steps and jobs."
+            echo "This PR does not change the action's source code.  Skipping subsequent steps and jobs."
           fi
 
       # The remaining steps in this build will use the env.HAS_CODE_CHANGES condition.  Setting it on each
@@ -99,7 +105,7 @@ jobs:
 
       - name: PR Source - ${{ env.PR_SOURCE }}
         if: env.HAS_CODE_CHANGES == 'true'
-        run: echo "The PR can come from a branch or a fork.  This PR is from a ${{ env.PR_SOURCE }}."
+        run: echo "PRs can come from a branch or a fork.  This PR is from a ${{ env.PR_SOURCE }}."
 
       - name: Checkout
         uses: actions/checkout@v3
@@ -112,7 +118,7 @@ jobs:
         if: env.HAS_CODE_CHANGES == 'true'
         uses: im-open/update-action-version-in-file@v1
         with:
-          file-to-update: ${{ inputs.readme-location }} # Default: './README.md'
+          file-to-update: ${{ inputs.readme-location }} # Default: 'README.md'
           action-name: ${{ inputs.action-name }}        # Default: 'github.repository'
           updated-version: ${{ env.NEXT_VERSION }}
 
@@ -127,41 +133,65 @@ jobs:
             echo "NEEDS_COMMIT=false" >> "$GITHUB_ENV"
           fi
 
-      - name: If there are outstanding changes - Construct failing workflow summary
+      - name: If there are outstanding changes - Construct failing workflow summary & comment
         if: env.HAS_CODE_CHANGES == 'true' &&  env.NEEDS_COMMIT == 'true'
         id: summary
         uses: actions/github-script@v6
         with:
           script: |
-            const buildCmd = '${{ inputs.build-command }}';
-            const hasBuildStep =  buildCmd && buildCmd.trim().length > 0;
             
-            const summary = `Before this PR can be merged, the following item(s) should be addressed to comply with the contribution guidelines:
-            - Please update every example in ${{ inputs.readme-location }} where this action is used  
-              - Each instance should be updated to: \`uses: ${{ inputs.action-name }}@${{ env.NEXT_VERSION }}\``;
+            const isFork = ${{env.IS_FORK}};
+            const hasBuildStep =  '${{ inputs.build-command }}' && '${{ inputs.build-command }}'.trim().length > 0;
+            
+            const repoLink =  'https://github.com/${{github.repository}}';
+            const ref = isFork ? '${{ github.sha }}' : '${{ github.event.pull_request.head.ref }}';
+
+            const contributionLink = `${repoLink}#contributing`;
+            const readmeLink = `${repoLink}/blob/${ref}/README.md#usage-examples`;
+
+            // Construct the workflow summary/PR comment
+            let instructions = `Before this PR can be merged, the following item(s) should be addressed to comply with the action's [Contribution Guidelines](${contributionLink}).
+            - Please update [README.md](${readmeLink}) usage examples with the next version.  Each instance of this action in the examples should be updated to: 
+              \`uses: ${{ inputs.action-name }}@${{ env.NEXT_VERSION }}\``;
+            
             if (hasBuildStep){
-              summary += `
-            - Please ensure the action has been recompiled by running: \`${{ inputs.build-command }}\` from the root of the repository`;
+              instructions += `
+            - Please ensure the action has been recompiled by running the following command from the root of the repository: 
+              \`${{ inputs.build-command }}\``;
             }
-            core.exportVariable('FAILURE_MESSAGE', summary);
+            console.log(instructions)
 
-      # This step will not run for forks because the GH_TOKEN cannot exceed 'read' for
-      # any scope. The token needs 'pull-requests:write' in order to create a comment.
-      - name: If there are outstanding changes - Comment on PR (branches only)
-        if: env.HAS_CODE_CHANGES == 'true' &&  env.NEEDS_COMMIT == 'true' && env.IS_FORK == 'false'
-        uses: actions/github-script@v6
-        with:
-          script: |
-            github.rest.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: '${{ env.FAILURE_MESSAGE }}'
-            })
+            // Comment on PR for branches.  For forks, the GH_TOKEN only has 'read' 
+            // permission on all scopes so a comment cannot be made on the PR.
+            if (!isFork) {
+              github.rest.issues.createComment({
+                issue_number: context.issue.number,
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                body: instructions
+              })
+            }
 
-      - name: If there are outstanding changes - Fail the workflow
-        if: env.HAS_CODE_CHANGES == 'true' && env.NEEDS_COMMIT == 'true'
-        run: |
-          echo '${{ env.FAILURE_MESSAGE }}' >> $GITHUB_STEP_SUMMARY
-          echo '::error::${{ env.FAILURE_MESSAGE }}'
-          exit 1
+            // Create the workflow summary
+            core.summary
+              .addRaw(instructions)
+              .write()
+
+            // Fail the build
+            core.setFailed(instructions);
+
+
+
+      # - name: If there are outstanding changes - Fail the workflow
+      #   if: always() && env.HAS_CODE_CHANGES == 'true' && env.NEEDS_COMMIT == 'true'
+      #   run: |
+      #     echo "::error::Before this PR can be merged, the following item(s) should be addressed to comply with the contribution guidelines:"
+      #     echo "  - Please update every example in the README.md file where this action is used.  Each instance should be updated to:"
+      #     echo "    uses: ${{ inputs.action-name }}@${{ env.NEXT_VERSION }}
+          
+      #     if [ "${{ env.HAS_BUILD_STEP }}" == "true" ]; then
+      #       echo " - Please ensure the action has been recompiled by running the following command from the root of the repository:"
+      #       echo "    '${{ inputs.build-command }}'"
+      #     fi
+          
+      #     exit 1
